/* Refined Detailing — shared page interactions. No frameworks needed. */
(()=>{
'use strict';
const PRICES={exterior:{small:50,medium:60,large:70},interior:{small:50,medium:60,large:70},complete:{small:90,medium:110,large:125}};
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('.nav');
if(menu&&nav){menu.addEventListener('click',()=>{const isOpen=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(isOpen));menu.setAttribute('aria-label',isOpen?'Close menu':'Open menu');menu.textContent=isOpen?'×':'☰'});nav.addEventListener('click',e=>{if(e.target.closest('a')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='☰'}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='☰'}})}
// Service page vehicle size selector.
const chooser=document.querySelector('[data-size-chooser]');
if(chooser){chooser.addEventListener('click',e=>{const button=e.target.closest('[data-size]');if(!button)return;const size=button.dataset.size;chooser.querySelectorAll('button').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});document.querySelectorAll('[data-price]').forEach(el=>{el.textContent='$'+PRICES[el.dataset.price][size]})})}
// Before and after range slider: works with mouse, touch and keyboard.
document.querySelectorAll('[data-compare]').forEach(root=>{const range=root.querySelector('input[type="range"]'),after=root.querySelector('.after'),handle=root.querySelector('.handle'),knob=root.querySelector('.knob');const update=()=>{const x=range.value+'%';after.style.clipPath=`inset(0 0 0 ${x})`;handle.style.left=x;knob.style.left=x};range.addEventListener('input',update);update()});
// Gallery filters with clear accessible pressed state.
const filters=document.querySelectorAll('[data-filter]');if(filters.length){filters.forEach(b=>b.addEventListener('click',()=>{const which=b.dataset.filter;filters.forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});document.querySelectorAll('[data-categories]').forEach(tile=>{tile.hidden=which!=='all'&&!tile.dataset.categories.split(' ').includes(which)})}))}
const lightbox=document.getElementById('video-lightbox');if(lightbox){const video=lightbox.querySelector('video'),close=()=>{video.pause();video.removeAttribute('src');video.load();lightbox.classList.remove('open');document.body.style.overflow='';};document.querySelectorAll('[data-video]').forEach(b=>b.addEventListener('click',()=>{video.src=b.dataset.video;lightbox.classList.add('open');document.body.style.overflow='hidden';video.play().catch(()=>{});lightbox.querySelector('.lightbox-close').focus()}));lightbox.querySelector('.lightbox-close').addEventListener('click',close);lightbox.addEventListener('click',e=>{if(e.target===lightbox)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&lightbox.classList.contains('open'))close()})}
// Booking price estimate and enquiry delivery.
const form=document.getElementById('booking-form');if(form){const date=form.querySelector('[name="preferred-date"]');const now=new Date();const yyyy=now.getFullYear(),mm=String(now.getMonth()+1).padStart(2,'0'),dd=String(now.getDate()).padStart(2,'0');date.min=`${yyyy}-${mm}-${dd}`;const qs=new URLSearchParams(location.search).get('service');if(PRICES[qs]){const radio=form.querySelector(`input[value="${qs}"]`);if(radio)radio.checked=true}
 const priceOut=document.getElementById('booking-price'),description=document.getElementById('booking-selection');const names={exterior:'Exterior detail',interior:'Interior detail',complete:'Inside & outside'},sizes={small:'Small vehicle',medium:'Medium vehicle',large:'Large vehicle'};
 const update=()=>{const selected=form.querySelector('input[name="service"]:checked'),size=form.querySelector('[name="vehicle-size"]').value;if(!selected||!PRICES[selected.value]||!size){priceOut.textContent='—';description.textContent='Select a service and vehicle size';return}priceOut.textContent='$'+PRICES[selected.value][size];description.textContent=names[selected.value]+' · '+sizes[size]};form.addEventListener('change',update);update();
 form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const data=new FormData(form);const pick=k=>String(data.get(k)||'');const selected=pick('service'),size=pick('vehicle-size');const lines=[`Name: ${pick('name')}`,`Phone: ${pick('phone')}`,`Email: ${pick('email')}`,`Service: ${names[selected]||selected}`,`Vehicle size: ${sizes[size]||size}`,`Vehicle: ${pick('vehicle')}`,`Suburb: ${pick('suburb')}`,`Preferred date: ${pick('preferred-date')}`,`Preferred time: ${pick('preferred-time')}`,`Details: ${pick('condition')||'None'}`,`Guide price: $${PRICES[selected]?.[size]??'TBC'}`];const intro="Hi Refined Detailing, I'd like to enquire about a booking.",outro="Please let me know if you're available and confirm the price. Thanks!";const body=[intro,'',...lines,'',outro].join('\n');const to='refined.detailing.newcastle@gmail.com',phone='0431484541',subject='Detailing booking enquiry — '+pick('name'),q=encodeURIComponent(subject),b=encodeURIComponent(body);const sms=`sms:${phone}?&body=${b}`,mailto=`mailto:${to}?subject=${q}&body=${b}`,gmail=`https://mail.google.com/mail/?view=cm&fs=1&to=${to}&su=${q}&body=${b}`;const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent);const notice=document.getElementById('mailto-notice');if(notice){notice.hidden=false;notice.textContent=mobile?'Your enquiry is ready as a text message. Press Send to finish. Nothing opened? ':'Your enquiry is ready in Gmail. Press Send there to finish. Nothing opened? ';const link=(href,label,blank)=>{const x=document.createElement('a');x.href=href;x.textContent=label;if(blank){x.target='_blank';x.rel='noopener'}return x};if(mobile)notice.append(link(sms,'Send as a text'),' or ',link(mailto,'email instead'),'.');else notice.append(link(gmail,'Open in Gmail',true),' or ',link(mailto,'open your email app'),'.')}if(mobile)location.href=sms;else window.open(gmail,'_blank','noopener')});}
})();
